// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dtmgimp.proto

package dtmgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DtmTransOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitResult    bool                   `protobuf:"varint,1,opt,name=WaitResult,proto3" json:"WaitResult,omitempty"`
	TimeoutToFail int64                  `protobuf:"varint,2,opt,name=TimeoutToFail,proto3" json:"TimeoutToFail,omitempty"`
	RetryInterval int64                  `protobuf:"varint,3,opt,name=RetryInterval,proto3" json:"RetryInterval,omitempty"`
	// repeated string PassthroughHeaders = 4; // depreceated
	BranchHeaders  map[string]string `protobuf:"bytes,5,rep,name=BranchHeaders,proto3" json:"BranchHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestTimeout int64             `protobuf:"varint,6,opt,name=RequestTimeout,proto3" json:"RequestTimeout,omitempty"`
	RetryLimit     int64             `protobuf:"varint,7,opt,name=RetryLimit,proto3" json:"RetryLimit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DtmTransOptions) Reset() {
	*x = DtmTransOptions{}
	mi := &file_dtmgimp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmTransOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmTransOptions) ProtoMessage() {}

func (x *DtmTransOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmTransOptions.ProtoReflect.Descriptor instead.
func (*DtmTransOptions) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{0}
}

func (x *DtmTransOptions) GetWaitResult() bool {
	if x != nil {
		return x.WaitResult
	}
	return false
}

func (x *DtmTransOptions) GetTimeoutToFail() int64 {
	if x != nil {
		return x.TimeoutToFail
	}
	return 0
}

func (x *DtmTransOptions) GetRetryInterval() int64 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

func (x *DtmTransOptions) GetBranchHeaders() map[string]string {
	if x != nil {
		return x.BranchHeaders
	}
	return nil
}

func (x *DtmTransOptions) GetRequestTimeout() int64 {
	if x != nil {
		return x.RequestTimeout
	}
	return 0
}

func (x *DtmTransOptions) GetRetryLimit() int64 {
	if x != nil {
		return x.RetryLimit
	}
	return 0
}

// DtmRequest request sent to dtm server
type DtmRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gid            string                 `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	TransType      string                 `protobuf:"bytes,2,opt,name=TransType,proto3" json:"TransType,omitempty"`
	TransOptions   *DtmTransOptions       `protobuf:"bytes,3,opt,name=TransOptions,proto3" json:"TransOptions,omitempty"`
	CustomedData   string                 `protobuf:"bytes,4,opt,name=CustomedData,proto3" json:"CustomedData,omitempty"`
	BinPayloads    [][]byte               `protobuf:"bytes,5,rep,name=BinPayloads,proto3" json:"BinPayloads,omitempty"`     // for Msg/Saga/Workflow branch payloads
	QueryPrepared  string                 `protobuf:"bytes,6,opt,name=QueryPrepared,proto3" json:"QueryPrepared,omitempty"` // for Msg
	Steps          string                 `protobuf:"bytes,7,opt,name=Steps,proto3" json:"Steps,omitempty"`
	ReqExtra       map[string]string      `protobuf:"bytes,8,rep,name=ReqExtra,proto3" json:"ReqExtra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RollbackReason string                 `protobuf:"bytes,9,opt,name=RollbackReason,proto3" json:"RollbackReason,omitempty"`
	NextCronTime   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=NextCronTime,proto3" json:"NextCronTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DtmRequest) Reset() {
	*x = DtmRequest{}
	mi := &file_dtmgimp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmRequest) ProtoMessage() {}

func (x *DtmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmRequest.ProtoReflect.Descriptor instead.
func (*DtmRequest) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{1}
}

func (x *DtmRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *DtmRequest) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *DtmRequest) GetTransOptions() *DtmTransOptions {
	if x != nil {
		return x.TransOptions
	}
	return nil
}

func (x *DtmRequest) GetCustomedData() string {
	if x != nil {
		return x.CustomedData
	}
	return ""
}

func (x *DtmRequest) GetBinPayloads() [][]byte {
	if x != nil {
		return x.BinPayloads
	}
	return nil
}

func (x *DtmRequest) GetQueryPrepared() string {
	if x != nil {
		return x.QueryPrepared
	}
	return ""
}

func (x *DtmRequest) GetSteps() string {
	if x != nil {
		return x.Steps
	}
	return ""
}

func (x *DtmRequest) GetReqExtra() map[string]string {
	if x != nil {
		return x.ReqExtra
	}
	return nil
}

func (x *DtmRequest) GetRollbackReason() string {
	if x != nil {
		return x.RollbackReason
	}
	return ""
}

func (x *DtmRequest) GetNextCronTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NextCronTime
	}
	return nil
}

type DtmGidReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtmGidReply) Reset() {
	*x = DtmGidReply{}
	mi := &file_dtmgimp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmGidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmGidReply) ProtoMessage() {}

func (x *DtmGidReply) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmGidReply.ProtoReflect.Descriptor instead.
func (*DtmGidReply) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{2}
}

func (x *DtmGidReply) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type DtmBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	TransType     string                 `protobuf:"bytes,2,opt,name=TransType,proto3" json:"TransType,omitempty"`
	BranchID      string                 `protobuf:"bytes,3,opt,name=BranchID,proto3" json:"BranchID,omitempty"`
	Op            string                 `protobuf:"bytes,4,opt,name=Op,proto3" json:"Op,omitempty"`
	Data          map[string]string      `protobuf:"bytes,5,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BusiPayload   []byte                 `protobuf:"bytes,6,opt,name=BusiPayload,proto3" json:"BusiPayload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtmBranchRequest) Reset() {
	*x = DtmBranchRequest{}
	mi := &file_dtmgimp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmBranchRequest) ProtoMessage() {}

func (x *DtmBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmBranchRequest.ProtoReflect.Descriptor instead.
func (*DtmBranchRequest) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{3}
}

func (x *DtmBranchRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *DtmBranchRequest) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *DtmBranchRequest) GetBranchID() string {
	if x != nil {
		return x.BranchID
	}
	return ""
}

func (x *DtmBranchRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DtmBranchRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DtmBranchRequest) GetBusiPayload() []byte {
	if x != nil {
		return x.BusiPayload
	}
	return nil
}

type DtmProgressesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *DtmTransaction        `protobuf:"bytes,1,opt,name=Transaction,json=transaction,proto3" json:"Transaction,omitempty"`
	Progresses    []*DtmProgress         `protobuf:"bytes,2,rep,name=Progresses,json=progresses,proto3" json:"Progresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtmProgressesReply) Reset() {
	*x = DtmProgressesReply{}
	mi := &file_dtmgimp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmProgressesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmProgressesReply) ProtoMessage() {}

func (x *DtmProgressesReply) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmProgressesReply.ProtoReflect.Descriptor instead.
func (*DtmProgressesReply) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{4}
}

func (x *DtmProgressesReply) GetTransaction() *DtmTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *DtmProgressesReply) GetProgresses() []*DtmProgress {
	if x != nil {
		return x.Progresses
	}
	return nil
}

type DtmTransaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gid            string                 `protobuf:"bytes,1,opt,name=Gid,json=gid,proto3" json:"Gid,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	RollbackReason string                 `protobuf:"bytes,3,opt,name=RollbackReason,json=rollback_reason,proto3" json:"RollbackReason,omitempty"`
	Result         string                 `protobuf:"bytes,4,opt,name=Result,json=result,proto3" json:"Result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DtmTransaction) Reset() {
	*x = DtmTransaction{}
	mi := &file_dtmgimp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmTransaction) ProtoMessage() {}

func (x *DtmTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmTransaction.ProtoReflect.Descriptor instead.
func (*DtmTransaction) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{5}
}

func (x *DtmTransaction) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *DtmTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DtmTransaction) GetRollbackReason() string {
	if x != nil {
		return x.RollbackReason
	}
	return ""
}

func (x *DtmTransaction) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DtmProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	BinData       []byte                 `protobuf:"bytes,2,opt,name=BinData,json=bin_data,proto3" json:"BinData,omitempty"`
	BranchID      string                 `protobuf:"bytes,3,opt,name=BranchID,json=branch_id,proto3" json:"BranchID,omitempty"`
	Op            string                 `protobuf:"bytes,4,opt,name=Op,json=op,proto3" json:"Op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtmProgress) Reset() {
	*x = DtmProgress{}
	mi := &file_dtmgimp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmProgress) ProtoMessage() {}

func (x *DtmProgress) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmProgress.ProtoReflect.Descriptor instead.
func (*DtmProgress) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{6}
}

func (x *DtmProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DtmProgress) GetBinData() []byte {
	if x != nil {
		return x.BinData
	}
	return nil
}

func (x *DtmProgress) GetBranchID() string {
	if x != nil {
		return x.BranchID
	}
	return ""
}

func (x *DtmProgress) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

type DtmTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	URL           string                 `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=Remark,proto3" json:"Remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtmTopicRequest) Reset() {
	*x = DtmTopicRequest{}
	mi := &file_dtmgimp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmTopicRequest) ProtoMessage() {}

func (x *DtmTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgimp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmTopicRequest.ProtoReflect.Descriptor instead.
func (*DtmTopicRequest) Descriptor() ([]byte, []int) {
	return file_dtmgimp_proto_rawDescGZIP(), []int{7}
}

func (x *DtmTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DtmTopicRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *DtmTopicRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_dtmgimp_proto protoreflect.FileDescriptor

const file_dtmgimp_proto_rawDesc = "" +
	"\n" +
	"\rdtmgimp.proto\x12\adtmgimp\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x02\n" +
	"\x0fDtmTransOptions\x12\x1e\n" +
	"\n" +
	"WaitResult\x18\x01 \x01(\bR\n" +
	"WaitResult\x12$\n" +
	"\rTimeoutToFail\x18\x02 \x01(\x03R\rTimeoutToFail\x12$\n" +
	"\rRetryInterval\x18\x03 \x01(\x03R\rRetryInterval\x12Q\n" +
	"\rBranchHeaders\x18\x05 \x03(\v2+.dtmgimp.DtmTransOptions.BranchHeadersEntryR\rBranchHeaders\x12&\n" +
	"\x0eRequestTimeout\x18\x06 \x01(\x03R\x0eRequestTimeout\x12\x1e\n" +
	"\n" +
	"RetryLimit\x18\a \x01(\x03R\n" +
	"RetryLimit\x1a@\n" +
	"\x12BranchHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x03\n" +
	"\n" +
	"DtmRequest\x12\x10\n" +
	"\x03Gid\x18\x01 \x01(\tR\x03Gid\x12\x1c\n" +
	"\tTransType\x18\x02 \x01(\tR\tTransType\x12<\n" +
	"\fTransOptions\x18\x03 \x01(\v2\x18.dtmgimp.DtmTransOptionsR\fTransOptions\x12\"\n" +
	"\fCustomedData\x18\x04 \x01(\tR\fCustomedData\x12 \n" +
	"\vBinPayloads\x18\x05 \x03(\fR\vBinPayloads\x12$\n" +
	"\rQueryPrepared\x18\x06 \x01(\tR\rQueryPrepared\x12\x14\n" +
	"\x05Steps\x18\a \x01(\tR\x05Steps\x12=\n" +
	"\bReqExtra\x18\b \x03(\v2!.dtmgimp.DtmRequest.ReqExtraEntryR\bReqExtra\x12&\n" +
	"\x0eRollbackReason\x18\t \x01(\tR\x0eRollbackReason\x12>\n" +
	"\fNextCronTime\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\fNextCronTime\x1a;\n" +
	"\rReqExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\vDtmGidReply\x12\x10\n" +
	"\x03Gid\x18\x01 \x01(\tR\x03Gid\"\x82\x02\n" +
	"\x10DtmBranchRequest\x12\x10\n" +
	"\x03Gid\x18\x01 \x01(\tR\x03Gid\x12\x1c\n" +
	"\tTransType\x18\x02 \x01(\tR\tTransType\x12\x1a\n" +
	"\bBranchID\x18\x03 \x01(\tR\bBranchID\x12\x0e\n" +
	"\x02Op\x18\x04 \x01(\tR\x02Op\x127\n" +
	"\x04Data\x18\x05 \x03(\v2#.dtmgimp.DtmBranchRequest.DataEntryR\x04Data\x12 \n" +
	"\vBusiPayload\x18\x06 \x01(\fR\vBusiPayload\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x12DtmProgressesReply\x129\n" +
	"\vTransaction\x18\x01 \x01(\v2\x17.dtmgimp.DtmTransactionR\vtransaction\x124\n" +
	"\n" +
	"Progresses\x18\x02 \x03(\v2\x14.dtmgimp.DtmProgressR\n" +
	"progresses\"{\n" +
	"\x0eDtmTransaction\x12\x10\n" +
	"\x03Gid\x18\x01 \x01(\tR\x03gid\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0eRollbackReason\x18\x03 \x01(\tR\x0frollback_reason\x12\x16\n" +
	"\x06Result\x18\x04 \x01(\tR\x06result\"m\n" +
	"\vDtmProgress\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\aBinData\x18\x02 \x01(\fR\bbin_data\x12\x1b\n" +
	"\bBranchID\x18\x03 \x01(\tR\tbranch_id\x12\x0e\n" +
	"\x02Op\x18\x04 \x01(\tR\x02op\"Q\n" +
	"\x0fDtmTopicRequest\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\x12\x10\n" +
	"\x03URL\x18\x02 \x01(\tR\x03URL\x12\x16\n" +
	"\x06Remark\x18\x03 \x01(\tR\x06Remark2\xbf\x04\n" +
	"\x03Dtm\x128\n" +
	"\x06NewGid\x12\x16.google.protobuf.Empty\x1a\x14.dtmgimp.DtmGidReply\"\x00\x127\n" +
	"\x06Submit\x12\x13.dtmgimp.DtmRequest\x1a\x16.google.protobuf.Empty\"\x00\x128\n" +
	"\aPrepare\x12\x13.dtmgimp.DtmRequest\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\x05Abort\x12\x13.dtmgimp.DtmRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\x0eRegisterBranch\x12\x19.dtmgimp.DtmBranchRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\x0fPrepareWorkflow\x12\x13.dtmgimp.DtmRequest\x1a\x1b.dtmgimp.DtmProgressesReply\"\x00\x12?\n" +
	"\tSubscribe\x12\x18.dtmgimp.DtmTopicRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\vUnsubscribe\x12\x18.dtmgimp.DtmTopicRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\vDeleteTopic\x12\x18.dtmgimp.DtmTopicRequest\x1a\x16.google.protobuf.Empty\"\x00B\n" +
	"Z\b./dtmgpbb\x06proto3"

var (
	file_dtmgimp_proto_rawDescOnce sync.Once
	file_dtmgimp_proto_rawDescData []byte
)

func file_dtmgimp_proto_rawDescGZIP() []byte {
	file_dtmgimp_proto_rawDescOnce.Do(func() {
		file_dtmgimp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtmgimp_proto_rawDesc), len(file_dtmgimp_proto_rawDesc)))
	})
	return file_dtmgimp_proto_rawDescData
}

var file_dtmgimp_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dtmgimp_proto_goTypes = []any{
	(*DtmTransOptions)(nil),       // 0: dtmgimp.DtmTransOptions
	(*DtmRequest)(nil),            // 1: dtmgimp.DtmRequest
	(*DtmGidReply)(nil),           // 2: dtmgimp.DtmGidReply
	(*DtmBranchRequest)(nil),      // 3: dtmgimp.DtmBranchRequest
	(*DtmProgressesReply)(nil),    // 4: dtmgimp.DtmProgressesReply
	(*DtmTransaction)(nil),        // 5: dtmgimp.DtmTransaction
	(*DtmProgress)(nil),           // 6: dtmgimp.DtmProgress
	(*DtmTopicRequest)(nil),       // 7: dtmgimp.DtmTopicRequest
	nil,                           // 8: dtmgimp.DtmTransOptions.BranchHeadersEntry
	nil,                           // 9: dtmgimp.DtmRequest.ReqExtraEntry
	nil,                           // 10: dtmgimp.DtmBranchRequest.DataEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_dtmgimp_proto_depIdxs = []int32{
	8,  // 0: dtmgimp.DtmTransOptions.BranchHeaders:type_name -> dtmgimp.DtmTransOptions.BranchHeadersEntry
	0,  // 1: dtmgimp.DtmRequest.TransOptions:type_name -> dtmgimp.DtmTransOptions
	9,  // 2: dtmgimp.DtmRequest.ReqExtra:type_name -> dtmgimp.DtmRequest.ReqExtraEntry
	11, // 3: dtmgimp.DtmRequest.NextCronTime:type_name -> google.protobuf.Timestamp
	10, // 4: dtmgimp.DtmBranchRequest.Data:type_name -> dtmgimp.DtmBranchRequest.DataEntry
	5,  // 5: dtmgimp.DtmProgressesReply.Transaction:type_name -> dtmgimp.DtmTransaction
	6,  // 6: dtmgimp.DtmProgressesReply.Progresses:type_name -> dtmgimp.DtmProgress
	12, // 7: dtmgimp.Dtm.NewGid:input_type -> google.protobuf.Empty
	1,  // 8: dtmgimp.Dtm.Submit:input_type -> dtmgimp.DtmRequest
	1,  // 9: dtmgimp.Dtm.Prepare:input_type -> dtmgimp.DtmRequest
	1,  // 10: dtmgimp.Dtm.Abort:input_type -> dtmgimp.DtmRequest
	3,  // 11: dtmgimp.Dtm.RegisterBranch:input_type -> dtmgimp.DtmBranchRequest
	1,  // 12: dtmgimp.Dtm.PrepareWorkflow:input_type -> dtmgimp.DtmRequest
	7,  // 13: dtmgimp.Dtm.Subscribe:input_type -> dtmgimp.DtmTopicRequest
	7,  // 14: dtmgimp.Dtm.Unsubscribe:input_type -> dtmgimp.DtmTopicRequest
	7,  // 15: dtmgimp.Dtm.DeleteTopic:input_type -> dtmgimp.DtmTopicRequest
	2,  // 16: dtmgimp.Dtm.NewGid:output_type -> dtmgimp.DtmGidReply
	12, // 17: dtmgimp.Dtm.Submit:output_type -> google.protobuf.Empty
	12, // 18: dtmgimp.Dtm.Prepare:output_type -> google.protobuf.Empty
	12, // 19: dtmgimp.Dtm.Abort:output_type -> google.protobuf.Empty
	12, // 20: dtmgimp.Dtm.RegisterBranch:output_type -> google.protobuf.Empty
	4,  // 21: dtmgimp.Dtm.PrepareWorkflow:output_type -> dtmgimp.DtmProgressesReply
	12, // 22: dtmgimp.Dtm.Subscribe:output_type -> google.protobuf.Empty
	12, // 23: dtmgimp.Dtm.Unsubscribe:output_type -> google.protobuf.Empty
	12, // 24: dtmgimp.Dtm.DeleteTopic:output_type -> google.protobuf.Empty
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dtmgimp_proto_init() }
func file_dtmgimp_proto_init() {
	if File_dtmgimp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtmgimp_proto_rawDesc), len(file_dtmgimp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dtmgimp_proto_goTypes,
		DependencyIndexes: file_dtmgimp_proto_depIdxs,
		MessageInfos:      file_dtmgimp_proto_msgTypes,
	}.Build()
	File_dtmgimp_proto = out.File
	file_dtmgimp_proto_goTypes = nil
	file_dtmgimp_proto_depIdxs = nil
}
