version: '3.3'
services:
  api:
    build: .
    environment:
      IS_DOCKER: 1
      DISABLE_LOCALHOST: 1
      RETRY_LIMIT: 6
    ports:
      - '9080:8080'
    volumes:
      - .:/app/dtm
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: Asia/shanghai
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
      ]
    ports:
      - '3306:3306'
