version: '3.3'
services:
  postgres:
    image: 'postgres:13'
    command: postgres --max_prepared_transactions=1000
    environment:
      POSTGRES_PASSWORD: mysecretpassword

    ports:
      - '5432:5432'
