version: '3.3'
services:
  mysql:
    image: 'mysql:5.7'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    ports:
      - '3306:3306'
  postgres:
    image: 'postgres:13'
    command: postgres --max_prepared_transactions=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dtm

    ports:
      - '5432:5432'
  redis:
    image: 'redis'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '6379:6379'
  mongo:
    image: yedf/mongo-rs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '27017:27017'
