FROM golang:1.16.6-alpine3.14 as builder
WORKDIR /app/dtm
RUN go env -w GO111MODULE=on
# RUN go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
EXPOSE 8080
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" app/main.go

FROM alpine:3.14 as runner
COPY --from=builder /app/dtm/main /app/dtm/
ENV IS_DOCKER=1
WORKDIR /app/dtm
CMD ["/app/dtm/main", "dtmsvr"]
