run:
  deadline: 5m
  skip-dirs:
    - test
    - examples

linter-settings:
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - revive
    - goconst
    - gofmt
    - goimports
    - misspell
    - unparam

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - revive
