FROM golang as builder
WORKDIR /app/dtm
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
EXPOSE 8080
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" app/main.go

FROM scratch as runner
COPY --from=builder /app/dtm/main /app/dtm/main
ENV IS_DOCKER=1
CMD ["/app/dtm/main", "dtmsvr"]
