# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtm < Formula
  desc "A cross-language distributed transaction manager."
  homepage "https://d.dtm.pub"
  version "1.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dtm-labs/dtm/releases/download/v1.8.1/dtm_1.8.1_darwin_amd64.tar.gz"
      sha256 "8277820eac478f48fd6770f41eb2ec674dac1eddc66e4ebbd9c73eb41ae39548"

      def install
        bin.install "dtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dtm-labs/dtm/releases/download/v1.8.1/dtm_1.8.1_linux_amd64.tar.gz"
      sha256 "ce83774f50b9f121c5f54baf657555053f817af9efccb50d80a9854b7579807a"

      def install
        bin.install "dtm"
      end
    end
  end
end
