// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: dtmgrpc/workflow/wfpb/wf.proto

package wfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *WorkflowData) Reset() {
	*x = WorkflowData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtmgrpc_workflow_wfpb_wf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowData) ProtoMessage() {}

func (x *WorkflowData) ProtoReflect() protoreflect.Message {
	mi := &file_dtmgrpc_workflow_wfpb_wf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowData.ProtoReflect.Descriptor instead.
func (*WorkflowData) Descriptor() ([]byte, []int) {
	return file_dtmgrpc_workflow_wfpb_wf_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_dtmgrpc_workflow_wfpb_wf_proto protoreflect.FileDescriptor

var file_dtmgrpc_workflow_wfpb_wf_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x64, 0x74, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x2f, 0x77, 0x66, 0x70, 0x62, 0x2f, 0x77, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x32, 0x47, 0x0a, 0x08, 0x57,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x3b, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x77, 0x66, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dtmgrpc_workflow_wfpb_wf_proto_rawDescOnce sync.Once
	file_dtmgrpc_workflow_wfpb_wf_proto_rawDescData = file_dtmgrpc_workflow_wfpb_wf_proto_rawDesc
)

func file_dtmgrpc_workflow_wfpb_wf_proto_rawDescGZIP() []byte {
	file_dtmgrpc_workflow_wfpb_wf_proto_rawDescOnce.Do(func() {
		file_dtmgrpc_workflow_wfpb_wf_proto_rawDescData = protoimpl.X.CompressGZIP(file_dtmgrpc_workflow_wfpb_wf_proto_rawDescData)
	})
	return file_dtmgrpc_workflow_wfpb_wf_proto_rawDescData
}

var file_dtmgrpc_workflow_wfpb_wf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dtmgrpc_workflow_wfpb_wf_proto_goTypes = []interface{}{
	(*WorkflowData)(nil),  // 0: workflow.WorkflowData
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_dtmgrpc_workflow_wfpb_wf_proto_depIdxs = []int32{
	0, // 0: workflow.Workflow.Execute:input_type -> workflow.WorkflowData
	1, // 1: workflow.Workflow.Execute:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dtmgrpc_workflow_wfpb_wf_proto_init() }
func file_dtmgrpc_workflow_wfpb_wf_proto_init() {
	if File_dtmgrpc_workflow_wfpb_wf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dtmgrpc_workflow_wfpb_wf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dtmgrpc_workflow_wfpb_wf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dtmgrpc_workflow_wfpb_wf_proto_goTypes,
		DependencyIndexes: file_dtmgrpc_workflow_wfpb_wf_proto_depIdxs,
		MessageInfos:      file_dtmgrpc_workflow_wfpb_wf_proto_msgTypes,
	}.Build()
	File_dtmgrpc_workflow_wfpb_wf_proto = out.File
	file_dtmgrpc_workflow_wfpb_wf_proto_rawDesc = nil
	file_dtmgrpc_workflow_wfpb_wf_proto_goTypes = nil
	file_dtmgrpc_workflow_wfpb_wf_proto_depIdxs = nil
}
