name: Build Docker
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Version
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo RELEASE_VERSION: ${RELEASE_VERSION}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3

      - name: Create Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            feelguuds/dtx-manager
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./helper/Dockerfile-release
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
